### ISSUE TITLE
backlog

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/lab-presentation#2]
# Backlog 

## Travail à faire

- Création de la liste des tâches
- Validation avec le formateur
- Création des issues
- Changement les noms des fichier dans le dossier backlog :
    - Ordre.Titre_issue.Numero_issue.md
- Les issues sont enregistrer dans des sous-dossiers qui représente des labels des issues

## Livrable
- docs/0.table-de-matiere/*
- backlog/*
- README.md je vais ajouter seleument les liens des issues

**Comment by husseinbouik** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue

**Comment by essarraj-fouad** [comment]
Il faut respecter les templates de description des tâches
