### ISSUE TITLE
init-lab

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/lab-presentation#3]
# init-lab

## Travail à faire
- Élaboration d'un rapport sans contenu avec les pages et leurs titres
- Création d'une présentation sans contenu, mais avec les titres des diapositives

## Livrable
- backlog/sous-tâche/1.init-lab.3.md
- docs/* 
- index.md
- Readme.json : je vais ajouter seleument le lien de rapport
- Readme.md  : je vais ajouter seleument le lien de rapport

**Comment by husseinbouik** [comment]
- le pullrequest a une conflit
