### ISSUE TITLE
init-presentation

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/lab-presentation#4]
# Init presentation

## Travail à faire

Création d'une présentation sans contenu, mais avec les titres des diapositives

## Livrable
- Backlog /sous-tâche/*
- docs/* : je vais modifier tous les fichier dans cette répertoire
- docs/_layouts/presentation.html
- presentation.md
- index.md
- Readme.json : je vais ajouter seulement le lien de présentation
- Readme.md : je vais ajouter seulement le lien de présentation

**Comment by husseinbouik** [comment]
- le pullrequest a une conflit
